name: Release Extensions

on:
    push:
        branches:
        - main
        tags:
          - 'v*.*.*'

    pull_request:
        branches:
        - main

    workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  extensions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - uses: actions/checkout@v4
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0

    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true

    # Set version
    - name: Build
      run: |
        $Version = "${{ steps.version.outputs.semVer }}"
        ./build/build.ps1 -Version $Version

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      with:
        commit_message: "Bump version to ${{ steps.version.outputs.semVer }}"
        tagging_message: "v${{ steps.version.outputs.semVer }}"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      with:
        name: ${{ steps.version.outputs.semVer }}
        tag_name: v${{ steps.version.outputs.semVer }}
        files: build/*.zip
        generate_release_notes: true

    # Upload the packages: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Extensions
        path: build/*.zip